### ISSUE TITLE
No Navigation Possible while viewing deck! See comments.

### ISSUE THREAD

**Issue by kylebakerio** [finetype/mindseal#115]
1. If you press the hamburger to pull out the menu, you make mithril pause
2. If the menu is just out because the screen is wide enough, and you click one of its buttons, you make mithril pause
3. If you reach the end of the deck before trying to navigate, you get none of these problems.

This is likely related to the fix for #81, which involved a m.startComputation() that never got ended--probably just need an m.endComputation() thrown into the 'else' statement on App.animate() that catches superfluous animations.

**Comment by finetype** [comment]
1. If you press the hamburger to pull out the menu, you make mithril pause
2. If the menu is just out because the screen is wide enough, and you click one of its buttons, you make mithril pause
3. If you reach the end of the deck before trying to navigate, you get none of these problems.

This is likely related to the fix for #81, which involved a m.startComputation() that never got ended--probably just need an m.endComputation() thrown into the 'else' statement on App.animate() that catches superfluous animations.
